name: SmashHit-Unoriginal
version: "1.1"
author: "frash23, Speentie8081"
main: "com.frash23.smashhit.SmashHit"
depend: [ ProtocolLib ]
softdepend: [ WorldGuard ]
commands:
  smashhit:
    aliases: [ sh ]
    permission: smashhit.admin